shared:
  image: centos:centos7
  steps:
    - echo: echo hoge

jobs:
  join1:
    requires: [ ~sd@12973:first ]

  join2:
    requires: [ ~sd@12973:first ]

  join3:
    requires: [ ~sd@12973:second ]

  join4:
    requires: [ ~sd@12973:second ]
