shared:
  image: centos:centos7
  steps:
    - echo: echo hoge

jobs:
  first:
    requires: [ ~commit ]

  second:
    requires: [ sd@12974:join1, sd@12974:join2 ]

  third:
    requires: [ sd@12974:join3, sd@12974:join4 ]

  fourth:
    requires: [ ~sd@12974:join1, second ]

  fifth:
    requires: [ sd@12974:join1 ]
